spring:
  datasource:
    url: jdbc:h2:mem:telemetry
    username: sa
    password:


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


server:
  port: 8082

app:
  message:
    welcome: "Let's manage our telemetry efficiently!"